name: Upload Python Package

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v1
    - name: Prepare environment
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      uses: actions/setup-python@v1
    - name: Build package
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      run: |
        pip install wheel
        python setup.py sdist bdist_wheel
    - name: Publish package
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
